### ISSUE TITLE
Suggestion: a small backlog of events

### ISSUE THREAD

**Issue by badhamunaptra** [SteemSports/BuildTeamNotifier#2]
Suggesting a backlog of a few events (can they be stored within the extension itself?) - consider the situation, where users opens the notifications, then has to click somewhere else, for example another browser tab - and then the notifications are gone (happened to me).

**Comment by Kostronor** [comment]
I noticed that the extension looses all data when changing the browser tab on chrome. Best would be to have the last 100 or 1000? messages saved in a localstorage or so

**Comment by Raycoms** [comment]
Done
