### ISSUE TITLE
Bug: Dismissing issues in the notifier browser extension dismisses always the lowest one on the list

### ISSUE THREAD

**Issue by badhamunaptra** [SteemSports/BuildTeamNotifier#3]
An example - i had multiple notifications, i wanted to dismiss the topmost one by clicking on the X. Clicking that, always the lowest one on the list disappeared.

Clicking on the X (marked)
![1](https://user-images.githubusercontent.com/32394463/31045281-a7566a84-a5e8-11e7-952a-563cddb4430d.PNG)

The wrong one disappeared
![2](https://user-images.githubusercontent.com/32394463/31045282-b662687a-a5e8-11e7-9503-4a9f48b1a2b2.PNG)

**Comment by Raycoms** [comment]
Fixed in the newest version on Firefox, chrome being uploaded right now.
